version: '3.3'
volumes:
  static_value:
  media_value:
  db_value:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
  
  backend:
      image: daniyarchik/foodgram_backend:latest
      container_name: foodgram-back
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      depends_on:
        - db
      env_file:
        - .env

  frontend:
    image: daniyarchik/foodgram_frontend:latest
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static
      - media_value:/var/html/media
    depends_on:
      - backend