# Generated by Django 3.2.3 on 2024-10-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20241017_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите вашу электронную почту', max_length=256, verbose_name='Электронная почта'),
        ),
    ]
