# Generated by Django 3.2.6 on 2024-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Добавьте ваш аватар', upload_to='users/avatars', verbose_name='Аватар'),
        ),
    ]
