# Generated by Django 3.2.6 on 2024-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='subscriptionuser',
            constraint=models.UniqueConstraint(fields=('author', 'subscriber'), name='unique_subscription'),
        ),
    ]
