# Generated by Django 3.2.6 on 2024-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241028_1503'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionuser',
            name='unique_subscription',
        ),
        migrations.RenameField(
            model_name='subscriptionuser',
            old_name='subscriber',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='subscriptionuser',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique_subscription'),
        ),
    ]
